(function () {
  "use strict";

  window.OSSUARY_AUDIO_SOUNDS = [
    { id: "debug-skull-eyes-activation", category: "debug", file: "assets/audio/skull_eyes_activation.ogg", bus: "DEBUG", volume: 1, priority: 10, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 80 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["debug", "skull-eyes"], enabled: true },

    { id: "ui-button-click", category: "ui", file: "assets/audio/ui/button_click.ogg", bus: "BUTTONS", volume: 0.8, priority: 50, loop: false, preload: false, cooldown: 40, fade: { inMs: 0, outMs: 30 }, pool: 3, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["ui"], enabled: false },
    { id: "ui-button-error", category: "ui", file: "assets/audio/ui/button_error.ogg", bus: "BUTTONS", volume: 0.8, priority: 55, loop: false, preload: false, cooldown: 80, fade: { inMs: 0, outMs: 30 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["ui"], enabled: false },

    { id: "reel-mechanism-start", category: "reels", file: "assets/audio/reels/reel_mechanism_start.wav", bus: "REELS", volume: 0.5, priority: 60, loop: false, preload: true, cooldown: 250, fade: { inMs: 0, outMs: 40 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["reels", "mechanism", "start"], enabled: true },
    { id: "reel-spin-start", category: "reels", file: "assets/audio/reels/spin_start.wav", bus: "REELS", volume: 0.22, priority: 50, loop: true, preload: true, cooldown: 120, fade: { inMs: 0, outMs: 60 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["reels", "spin"], enabled: true },
    { id: "reel-stop", category: "reels", file: "assets/audio/reels/reel_stop.wav", bus: "REELS", volume: 0.4, priority: 50, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 40 }, pool: 4, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["reels", "stop"], enabled: true },

    { id: "music-normal", category: "music", file: "assets/audio/music/fondo_juego_normal.wav", bus: "MUSIC", volume: 0.55, priority: 35, loop: true, preload: true, cooldown: 0, fade: { inMs: 900, outMs: 900 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["music", "base"], enabled: true },
    { id: "music-bonus", category: "music", file: "assets/audio/music/fondo_juego_bonus.wav", bus: "MUSIC", volume: 0.6, priority: 36, loop: true, preload: true, cooldown: 0, fade: { inMs: 900, outMs: 900 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["music", "bonus"], enabled: true },
    { id: "music-ruleta", category: "music", file: "assets/audio/music/fondo_juego_ruleta.wav", bus: "MUSIC", volume: 0.62, priority: 37, loop: true, preload: true, cooldown: 0, fade: { inMs: 700, outMs: 700 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["music", "ruleta"], enabled: true },

    { id: "bonus-lock", category: "bonus", file: "assets/audio/bonus/rib_lock.ogg", bus: "BONUS", volume: 1, priority: 70, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 80 }, pool: 3, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "lock"], enabled: false },
    { id: "rib1-blade-fall", category: "bonus", file: "assets/audio/bonus/rib1_blade_fall.mp3", bus: "BONUS", volume: 0.95, priority: 78, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 90 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "rib1", "blade", "fall"], enabled: true },
    { id: "rib1-bonus-respin-loop", category: "bonus", file: "assets/audio/bonus/rib1_bonus_respin_loop.wav", bus: "BONUS", volume: 0.9, priority: 76, loop: true, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 160 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "rib1", "respin", "loop"], enabled: true },
    { id: "bonus-hand-cut", category: "bonus", file: "assets/audio/bonus/manos_cortandose.wav", bus: "BONUS", volume: 0.95, priority: 77, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 40 }, pool: 4, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "guillotine", "hand", "cut"], enabled: true },
    { id: "guadana-neck-line", category: "bonus", file: "assets/audio/bonus/guadana_neck_line.mp3", bus: "BONUS", volume: 0.95, priority: 78, loop: true, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 40 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "guadana", "neck", "line"], enabled: true },
    { id: "guadana-neck-cut", category: "bonus", file: "assets/audio/bonus/guadana_neck_cut.mp3", bus: "BONUS", volume: 0.98, priority: 79, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 50 }, pool: 3, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "guadana", "neck", "cut"], enabled: true },
    { id: "bonus-rope-pull", category: "bonus", file: "assets/audio/bonus/tirar_cuerda.wav", bus: "BONUS", volume: 0.95, priority: 78, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 40 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "sternum", "rope", "trigger"], enabled: true },
    { id: "bonus-candle-light", category: "bonus", file: "assets/audio/bonus/cerilla.mp3", bus: "BONUS", volume: 0.78, priority: 77, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 60 }, pool: 2, playbackRate: 1, maxDurationMs: 700, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "candle", "light"], enabled: true },
    { id: "bonus-multiplier-levelup", category: "bonus", file: "assets/audio/bonus/bonus_multiplier_levelup.mp3", bus: "BONUS", volume: 0.9, priority: 78, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 80 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "multiplier", "levelup", "blade"], enabled: true },
    { id: "bonus-multiplier-stick-blade", category: "bonus", file: "assets/audio/bonus/bonus_multiplier_stick_blade.mp3", bus: "BONUS", volume: 0.9, priority: 78, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 80 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "multiplier", "blade", "stick"], enabled: true },
    { id: "bonus-symbol-impact", category: "bonus", file: "assets/audio/bonus/bonus_symbol_impact.mp3", bus: "BONUS", volume: 0.95, priority: 78, loop: false, preload: true, cooldown: 140, fade: { inMs: 0, outMs: 80 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus", "symbol", "impact", "rib2", "rib3"], enabled: true },
    { id: "bonus-started", category: "bonus", file: "assets/audio/bonus/bonus_started.ogg", bus: "BONUS", volume: 1, priority: 75, loop: false, preload: false, cooldown: 0, fade: { inMs: 60, outMs: 150 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus"], enabled: false },
    { id: "bonus-completed", category: "bonus", file: "assets/audio/bonus/bonus_completed.ogg", bus: "BONUS", volume: 1, priority: 80, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 200 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus"], enabled: false },
    { id: "bonus-failed", category: "bonus", file: "assets/audio/bonus/bonus_failed.ogg", bus: "BONUS", volume: 1, priority: 75, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 200 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["bonus"], enabled: false },

    { id: "crow-stone-hit", category: "fx", file: "assets/audio/fx/cuervo_golpe.wav", bus: "SYMBOLS", volume: 0.95, priority: 74, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 60 }, pool: 3, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["fx", "small-blade", "crow", "stone", "hit"], enabled: true },
    { id: "crow-perch", category: "fx", file: "assets/audio/fx/cuervo_posarse.mp3", bus: "SYMBOLS", volume: 0.9, priority: 74, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 80 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["fx", "small-blade", "crow", "perch"], enabled: true },
    { id: "payline-win", category: "fx", file: "assets/audio/fx/linea_pago.mp3", bus: "SYMBOLS", volume: 1.4, priority: 60, loop: false, preload: true, cooldown: 400, fade: { inMs: 0, outMs: 80 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["fx", "payline", "win"], enabled: true },
    { id: "small-blade-tremble", category: "fx", file: "assets/audio/fx/small_blade_tremble.mp3", bus: "SYMBOLS", volume: 0.82, priority: 73, loop: true, preload: true, cooldown: 0, fade: { inMs: 35, outMs: 45 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["fx", "small-blade", "tremble"], enabled: true },
    { id: "small-blade-fall", category: "fx", file: "assets/audio/fx/small_blade_fall.mp3", bus: "SYMBOLS", volume: 0.9, priority: 74, loop: true, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 55 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["fx", "small-blade", "fall"], enabled: true },

    { id: "big-win-counter-loop", category: "wins", file: "assets/audio/fx/big_win_counter_loop.wav", bus: "BIGWIN", volume: 0.9, priority: 88, loop: true, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 0 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win", "counter", "loop"], enabled: true },
    { id: "big-win-counter-epic", category: "wins", file: "assets/audio/fx/big_win_counter_epic.wav", bus: "BIGWIN", volume: 1, priority: 92, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 0 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win", "counter", "epic"], enabled: true },
    { id: "big-win-counter-pause", category: "wins", file: "assets/audio/fx/big_win_counter_pause.mp3", bus: "BIGWIN", volume: 0.95, priority: 89, loop: false, preload: true, cooldown: 0, fade: { inMs: 0, outMs: 20 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win", "counter", "pause"], enabled: true },

    { id: "win-small", category: "wins", file: "assets/audio/wins/small_win.ogg", bus: "SYMBOLS", volume: 0.9, priority: 50, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 100 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win"], enabled: false },
    { id: "win-medium", category: "wins", file: "assets/audio/wins/medium_win.ogg", bus: "SYMBOLS", volume: 0.95, priority: 55, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 150 }, pool: 2, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win"], enabled: false },
    { id: "win-big", category: "wins", file: "assets/audio/wins/big_win.ogg", bus: "BIGWIN", volume: 1, priority: 85, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 200 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win"], enabled: false },
    { id: "win-mega", category: "wins", file: "assets/audio/wins/mega_win.ogg", bus: "BIGWIN", volume: 1, priority: 90, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 250 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win"], enabled: false },
    { id: "win-epic", category: "wins", file: "assets/audio/wins/epic_win.ogg", bus: "BIGWIN", volume: 1, priority: 95, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 300 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win"], enabled: false },
    { id: "win-jackpot", category: "wins", file: "assets/audio/wins/jackpot.ogg", bus: "BIGWIN", volume: 1, priority: 99, loop: false, preload: false, cooldown: 0, fade: { inMs: 0, outMs: 400 }, pool: 1, playbackRate: 1, pitch: 1, delay: 0, weight: 1, tags: ["win"], enabled: false }
  ];
})();
