(function () {
  "use strict";

  window.OSSUARY_AUDIO_RULES = [
    { event: "button_click", play: "ui-button-click" },
    { event: "button_error", play: "ui-button-error" },
    { event: "button_disabled", play: "ui-button-error" },

    { event: "spin_started", play: "reel-spin-start" },
    { event: "reel_started", play: "reel-mechanism-start" },
    { event: "reel_stopped", play: "reel-stop" },
    { event: "spin_finished", stop: "reel-spin-start" },
    { event: "bonus_reels_spin_started", play: "reel-spin-start" },
    { event: "bonus_reels_mechanism_started", play: "reel-mechanism-start" },
    { event: "bonus_reel_stopped", play: "reel-stop" },
    { event: "bonus_reels_spin_finished", stop: "reel-spin-start" },
    { event: "bonus_mode_spin_silence", stop: "reel-spin-start" },
    { event: "bonus_mode_spin_silence", stop: "reel-mechanism-start" },
    { event: "bonus_mode_spin_silence", stop: "rib1-bonus-respin-loop" },
    { event: "bonus_mode_spin_silence", stop: "small-blade-tremble" },
    { event: "bonus_mode_spin_silence", stop: "small-blade-fall" },

    { event: "bonus_lock", play: "bonus-lock" },
    { event: "bonus_symbol_landed_rib23", play: "bonus-symbol-impact" },
    { event: "small_blade_tremble_started", play: "small-blade-tremble" },
    { event: "small_blade_tremble_stopped", stop: "small-blade-tremble", fadeMs: 45 },
    { event: "small_blade_fall_started", play: "small-blade-fall" },
    { event: "small_blade_fall_stopped", stop: "small-blade-fall", fadeMs: 55 },
    { event: "rib1_blade_fall", play: "rib1-blade-fall" },
    { event: "rib1_bonus_respin_started", play: "rib1-bonus-respin-loop" },
    { event: "bonus_hand_cut", play: "bonus-hand-cut" },
    { event: "guadana_neck_line_started", play: "guadana-neck-line" },
    { event: "guadana_neck_line_stopped", stop: "guadana-neck-line", fadeMs: 30 },
    { event: "guadana_neck_cut", play: "guadana-neck-cut" },
    { event: "bonus_sternum_blade_triggered", play: "bonus-rope-pull" },
    { event: "bonus_candle_light", play: "bonus-candle-light" },
    { event: "bonus_multiplier_levelup", play: "bonus-multiplier-levelup" },
    { event: "bonus_multiplier_stuck_blade", play: "bonus-multiplier-stick-blade" },
    { event: "bonus_mode_started", play: "rib1-blade-fall" },
    { event: "bonus_mode_started", play: "rib1-bonus-respin-loop" },
    { event: "bonus_mode_completed", stop: "rib1-bonus-respin-loop", fadeMs: 160 },
    { event: "bonus_started", play: "bonus-started" },
    { event: "bonus_completed", stop: "rib1-bonus-respin-loop", fadeMs: 160 },
    { event: "bonus_failed", stop: "rib1-bonus-respin-loop", fadeMs: 160 },
    { event: "bonus_completed", play: "bonus-completed" },
    { event: "bonus_failed", play: "bonus-failed" },
    { event: "super_bonus", play: "bonus-started" },

    { event: "spin_finished", when: function (payload) { return payload && payload.winMultiple > 0 && payload.winMultiple < 5; }, play: "win-small" },
    { event: "spin_finished", when: function (payload) { return payload && payload.winMultiple >= 5 && payload.winMultiple < 15; }, play: "win-medium" },
    { event: "spin_finished", when: function (payload) { return payload && payload.winMultiple >= 15 && payload.winMultiple < 30; }, play: "win-big" },
    { event: "spin_finished", when: function (payload) { return payload && payload.winMultiple >= 30 && payload.winMultiple < 60; }, play: "win-mega" },
    { event: "spin_finished", when: function (payload) { return payload && payload.winMultiple >= 60; }, play: "win-epic" },
    { event: "jackpot", play: "win-jackpot" },

    { event: "crow_stone_hit", play: "crow-stone-hit" },
    { event: "crow_perch", play: "crow-perch" },
    { event: "payline_shown", play: "payline-win" },
    { event: "big_win_counter_counting_started", play: "big-win-counter-loop" },
    { event: "big_win_counter_counting_stopped", stop: "big-win-counter-loop", fadeMs: 0 },
    { event: "big_win_counter_pause", play: "big-win-counter-pause" },
    { event: "big_win_counter_beat", play: "big-win-counter-pause" },
    { event: "big_win_counter_completed", play: "big-win-counter-pause" },
    { event: "big_win_counter_epic_started", play: "big-win-counter-epic" },
    { event: "big_win_counter_hidden", stop: "big-win-counter-loop", fadeMs: 0 },
    { event: "big_win_counter_hidden", stop: "big-win-counter-epic", fadeMs: 180 },

    { event: "debug:skull-eyes-on", play: "debug-skull-eyes-activation" }
  ];
})();
